// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/openshift/hive/pkg/apis/hive/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterRelocateLister helps list ClusterRelocates.
// All objects returned here must be treated as read-only.
type ClusterRelocateLister interface {
	// List lists all ClusterRelocates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ClusterRelocate, err error)
	// Get retrieves the ClusterRelocate from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.ClusterRelocate, error)
	ClusterRelocateListerExpansion
}

// clusterRelocateLister implements the ClusterRelocateLister interface.
type clusterRelocateLister struct {
	indexer cache.Indexer
}

// NewClusterRelocateLister returns a new ClusterRelocateLister.
func NewClusterRelocateLister(indexer cache.Indexer) ClusterRelocateLister {
	return &clusterRelocateLister{indexer: indexer}
}

// List lists all ClusterRelocates in the indexer.
func (s *clusterRelocateLister) List(selector labels.Selector) (ret []*v1.ClusterRelocate, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ClusterRelocate))
	})
	return ret, err
}

// Get retrieves the ClusterRelocate from the index for a given name.
func (s *clusterRelocateLister) Get(name string) (*v1.ClusterRelocate, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("clusterrelocate"), name)
	}
	return obj.(*v1.ClusterRelocate), nil
}
