---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hive-operator
  namespace: hive
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-operator
  namespace: hive
  labels:
    control-plane: hive-operator
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: hive-operator
      controller-tools.k8s.io: "1.0"
  replicas: 1
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        control-plane: hive-operator
        controller-tools.k8s.io: "1.0"
    spec:
      serviceAccountName: hive-operator
      volumes:
      - name: kubectl-cache
        emptyDir: {}
      containers:
      # By default we will use the latest CI images published from hive master:
      - image: registry.svc.ci.openshift.org/openshift/hive-v4.0:hive
        imagePullPolicy: Always
        name: hive-operator
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        command:
          - /opt/services/hive-operator
          - --log-level
          - info
        volumeMounts:
        - name: kubectl-cache
          mountPath: /var/cache/kubectl
        env:
        - name: CLI_CACHE_DIR
          value: /var/cache/kubectl
        livenessProbe:
          httpGet:
            path: /debug/health
            port: 8080
          initialDelaySeconds: 10
          failureThreshold: 1
          periodSeconds: 10
      terminationGracePeriodSeconds: 10
