# This kustomize configuration deploys what is required for the hive-operator
# *without* OLM.
# Except:
# It does not contain a Namespace or a HiveConfig. These are created by app-sre.

# The CRD resources are synced automatically by the `build-app-sre-template` make target.
# The other resources should be curated manually.
resources:
- ../../config/operator/operator_role.yaml
- ../../config/operator/operator_role_binding.yaml
- ../../config/operator/operator_deployment.yaml
- ../../config/crds/hiveinternal.openshift.io_clustersyncleases.yaml
- ../../config/crds/hiveinternal.openshift.io_clustersyncs.yaml
- ../../config/crds/hiveinternal.openshift.io_fakeclusterinstalls.yaml
- ../../config/crds/hive.openshift.io_checkpoints.yaml
- ../../config/crds/hive.openshift.io_clusterclaims.yaml
- ../../config/crds/hive.openshift.io_clusterdeployments.yaml
- ../../config/crds/hive.openshift.io_clusterdeprovisions.yaml
- ../../config/crds/hive.openshift.io_clusterimagesets.yaml
- ../../config/crds/hive.openshift.io_clusterpools.yaml
- ../../config/crds/hive.openshift.io_clusterprovisions.yaml
- ../../config/crds/hive.openshift.io_clusterrelocates.yaml
- ../../config/crds/hive.openshift.io_clusterstates.yaml
- ../../config/crds/hive.openshift.io_dnszones.yaml
- ../../config/crds/hive.openshift.io_hiveconfigs.yaml
- ../../config/crds/hive.openshift.io_machinepoolnameleases.yaml
- ../../config/crds/hive.openshift.io_machinepools.yaml
- ../../config/crds/hive.openshift.io_selectorsyncidentityproviders.yaml
- ../../config/crds/hive.openshift.io_selectorsyncsets.yaml
- ../../config/crds/hive.openshift.io_syncidentityproviders.yaml
- ../../config/crds/hive.openshift.io_syncsets.yaml
- ../../config/crds/hive.openshift.io_clusterdeploymentcustomizations.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Use app-sre-supplied variables to pull the image for the current commit
# TODO: Pull by digest instead. Don't forget to address Disappearing Digest Syndrome.
images:
- digest: ${IMAGE_DIGEST}
  name: registry.ci.openshift.org/openshift/hive-v4.0:hive
  newName: ${REGISTRY_IMG}
patchesStrategicMerge:
- |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: hive-operator-role
    labels:
      managed.openshift.io/aggregate-to-dedicated-admins: cluster
- |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: hive-operator-rolebinding
  subjects:
  - kind: ServiceAccount
    name: hive-operator
    namespace: hive
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: hive-operator
  imagePullSecrets:
  - name: quay.io
