#FROM registry.access.redhat.com/ubi7/ubi
FROM openshift/origin-release:golang-1.13

# ssh-agent required for gathering logs in some situations:
RUN if ! rpm -q openssh-clients; then yum install -y openssh-clients && yum clean all && rm -rf /var/cache/yum/*; fi
#
# libvirt libraries required for running bare metal installer.
RUN yum install -y libvirt-devel && yum clean all && rm -rf /var/cache/yum/*


ADD bin/hiveadmission /opt/services/
ADD bin/operator /opt/services/hive-operator
ADD bin/manager /opt/services/
ADD bin/hiveutil /usr/bin/
ADD bin/hive-apiserver /opt/services

# Hacks to allow writing known_hosts, homedir is / by default in OpenShift.
# Bare metal installs need to write to $HOME/.cache, and $HOME/.ssh for as long as
# we're hitting libvirt over ssh. OpenShift will not let you write these directories
# by default so we must setup some permissions here.
ENV HOME /home/hive
RUN mkdir -p /home/hive && \
    chgrp -R 0 /home/hive && \
    chmod -R g=u /home/hive


# TODO: should this be the operator?
ENTRYPOINT ["/opt/services/manager"]
