#FROM registry.access.redhat.com/ubi7/ubi
FROM openshift/origin-release:golang-1.12

RUN chmod g+rw /etc/passwd

# ssh-agent required for gathering logs in some situations:
RUN if ! rpm -q openssh-clients; then yum install -y openssh-clients && yum clean all && rm -rf /var/cache/yum/*; fi
#
# libvirt libraries required for running bare metal installer.
RUN yum install -y libvirt-devel && yum clean all && rm -rf /var/cache/yum/*


ADD bin/hiveadmission /opt/services/
ADD bin/hive-operator /opt/services/
ADD bin/manager /opt/services/
ADD bin/hiveutil /usr/bin/
ADD bin/hive-apiserver /opt/services

# TODO: should this be the operator?
ENTRYPOINT ["/opt/services/manager"]
