// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/openstackclient/client.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	quotasets "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/quotasets"
	usage "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/usage"
	flavors "github.com/gophercloud/gophercloud/openstack/compute/v2/flavors"
	servers "github.com/gophercloud/gophercloud/openstack/compute/v2/servers"
	images "github.com/gophercloud/gophercloud/openstack/imageservice/v2/images"
	networks "github.com/gophercloud/gophercloud/openstack/networking/v2/networks"
	ports "github.com/gophercloud/gophercloud/openstack/networking/v2/ports"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateServerFromOpts mocks base method.
func (m *MockClient) CreateServerFromOpts(ctx context.Context, opts *servers.CreateOpts) (*servers.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServerFromOpts", ctx, opts)
	ret0, _ := ret[0].(*servers.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServerFromOpts indicates an expected call of CreateServerFromOpts.
func (mr *MockClientMockRecorder) CreateServerFromOpts(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServerFromOpts", reflect.TypeOf((*MockClient)(nil).CreateServerFromOpts), ctx, opts)
}

// CreateServerSnapshot mocks base method.
func (m *MockClient) CreateServerSnapshot(ctx context.Context, serverID, snapshotName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServerSnapshot", ctx, serverID, snapshotName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServerSnapshot indicates an expected call of CreateServerSnapshot.
func (mr *MockClientMockRecorder) CreateServerSnapshot(ctx, serverID, snapshotName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServerSnapshot", reflect.TypeOf((*MockClient)(nil).CreateServerSnapshot), ctx, serverID, snapshotName)
}

// DeleteImage mocks base method.
func (m *MockClient) DeleteImage(ctx context.Context, imageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, imageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockClientMockRecorder) DeleteImage(ctx, imageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockClient)(nil).DeleteImage), ctx, imageID)
}

// DeleteServer mocks base method.
func (m *MockClient) DeleteServer(ctx context.Context, serverID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServer", ctx, serverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServer indicates an expected call of DeleteServer.
func (mr *MockClientMockRecorder) DeleteServer(ctx, serverID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServer", reflect.TypeOf((*MockClient)(nil).DeleteServer), ctx, serverID)
}

// GetComputeQuotas mocks base method.
func (m *MockClient) GetComputeQuotas(ctx context.Context) (*quotasets.QuotaSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComputeQuotas", ctx)
	ret0, _ := ret[0].(*quotasets.QuotaSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComputeQuotas indicates an expected call of GetComputeQuotas.
func (mr *MockClientMockRecorder) GetComputeQuotas(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComputeQuotas", reflect.TypeOf((*MockClient)(nil).GetComputeQuotas), ctx)
}

// GetComputeUsage mocks base method.
func (m *MockClient) GetComputeUsage(ctx context.Context) (*usage.TenantUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComputeUsage", ctx)
	ret0, _ := ret[0].(*usage.TenantUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComputeUsage indicates an expected call of GetComputeUsage.
func (mr *MockClientMockRecorder) GetComputeUsage(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComputeUsage", reflect.TypeOf((*MockClient)(nil).GetComputeUsage), ctx)
}

// GetFlavorDetails mocks base method.
func (m *MockClient) GetFlavorDetails(ctx context.Context, flavorID string) (*flavors.Flavor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlavorDetails", ctx, flavorID)
	ret0, _ := ret[0].(*flavors.Flavor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlavorDetails indicates an expected call of GetFlavorDetails.
func (mr *MockClientMockRecorder) GetFlavorDetails(ctx, flavorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlavorDetails", reflect.TypeOf((*MockClient)(nil).GetFlavorDetails), ctx, flavorID)
}

// GetImage mocks base method.
func (m *MockClient) GetImage(ctx context.Context, imageID string) (*images.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, imageID)
	ret0, _ := ret[0].(*images.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockClientMockRecorder) GetImage(ctx, imageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockClient)(nil).GetImage), ctx, imageID)
}

// GetNetworkByName mocks base method.
func (m *MockClient) GetNetworkByName(ctx context.Context, networkName string) (*networks.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkByName", ctx, networkName)
	ret0, _ := ret[0].(*networks.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkByName indicates an expected call of GetNetworkByName.
func (mr *MockClientMockRecorder) GetNetworkByName(ctx, networkName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkByName", reflect.TypeOf((*MockClient)(nil).GetNetworkByName), ctx, networkName)
}

// GetServer mocks base method.
func (m *MockClient) GetServer(ctx context.Context, serverID string) (*servers.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServer", ctx, serverID)
	ret0, _ := ret[0].(*servers.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServer indicates an expected call of GetServer.
func (mr *MockClientMockRecorder) GetServer(ctx, serverID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServer", reflect.TypeOf((*MockClient)(nil).GetServer), ctx, serverID)
}

// GetServerSecurityGroupNames mocks base method.
func (m *MockClient) GetServerSecurityGroupNames(ctx context.Context, serverID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerSecurityGroupNames", ctx, serverID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerSecurityGroupNames indicates an expected call of GetServerSecurityGroupNames.
func (mr *MockClientMockRecorder) GetServerSecurityGroupNames(ctx, serverID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerSecurityGroupNames", reflect.TypeOf((*MockClient)(nil).GetServerSecurityGroupNames), ctx, serverID)
}

// ListImages mocks base method.
func (m *MockClient) ListImages(ctx context.Context, opts *images.ListOpts) ([]images.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImages", ctx, opts)
	ret0, _ := ret[0].([]images.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListImages indicates an expected call of ListImages.
func (mr *MockClientMockRecorder) ListImages(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImages", reflect.TypeOf((*MockClient)(nil).ListImages), ctx, opts)
}

// ListPorts mocks base method.
func (m *MockClient) ListPorts(ctx context.Context) ([]ports.Port, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPorts", ctx)
	ret0, _ := ret[0].([]ports.Port)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPorts indicates an expected call of ListPorts.
func (mr *MockClientMockRecorder) ListPorts(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPorts", reflect.TypeOf((*MockClient)(nil).ListPorts), ctx)
}

// ListServers mocks base method.
func (m *MockClient) ListServers(ctx context.Context, opts *servers.ListOpts) ([]servers.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServers", ctx, opts)
	ret0, _ := ret[0].([]servers.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServers indicates an expected call of ListServers.
func (mr *MockClientMockRecorder) ListServers(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServers", reflect.TypeOf((*MockClient)(nil).ListServers), ctx, opts)
}
