FROM hive-dev-base:latest

ADD bin/hiveadmission /opt/services/
ADD bin/operator /opt/services/hive-operator
ADD bin/manager /opt/services/
ADD bin/hiveutil /usr/bin/

# TODO: should this be the operator?
ENTRYPOINT ["/opt/services/manager"]
