---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.hive.openshift.io
  labels:
    api: hiveapi
    apiserver: "true"
  annotations:
    service.alpha.openshift.io/inject-cabundle: "true"
spec:
  group: hive.openshift.io
  groupPriorityMinimum: 2000
  service:
    name: hiveapi
    namespace: hive
  version: v1alpha1
  versionPriority: 10
