// Code generated by main. DO NOT EDIT.

package fake

import (
	hivev1 "github.com/openshift/hive/pkg/apis/hive/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSelectorSyncIdentityProviders implements SelectorSyncIdentityProviderInterface
type FakeSelectorSyncIdentityProviders struct {
	Fake *FakeHiveV1
}

var selectorsyncidentityprovidersResource = schema.GroupVersionResource{Group: "hive.openshift.io", Version: "v1", Resource: "selectorsyncidentityproviders"}

var selectorsyncidentityprovidersKind = schema.GroupVersionKind{Group: "hive.openshift.io", Version: "v1", Kind: "SelectorSyncIdentityProvider"}

// Get takes name of the selectorSyncIdentityProvider, and returns the corresponding selectorSyncIdentityProvider object, and an error if there is any.
func (c *FakeSelectorSyncIdentityProviders) Get(name string, options v1.GetOptions) (result *hivev1.SelectorSyncIdentityProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(selectorsyncidentityprovidersResource, name), &hivev1.SelectorSyncIdentityProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.SelectorSyncIdentityProvider), err
}

// List takes label and field selectors, and returns the list of SelectorSyncIdentityProviders that match those selectors.
func (c *FakeSelectorSyncIdentityProviders) List(opts v1.ListOptions) (result *hivev1.SelectorSyncIdentityProviderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(selectorsyncidentityprovidersResource, selectorsyncidentityprovidersKind, opts), &hivev1.SelectorSyncIdentityProviderList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hivev1.SelectorSyncIdentityProviderList{ListMeta: obj.(*hivev1.SelectorSyncIdentityProviderList).ListMeta}
	for _, item := range obj.(*hivev1.SelectorSyncIdentityProviderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested selectorSyncIdentityProviders.
func (c *FakeSelectorSyncIdentityProviders) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(selectorsyncidentityprovidersResource, opts))
}

// Create takes the representation of a selectorSyncIdentityProvider and creates it.  Returns the server's representation of the selectorSyncIdentityProvider, and an error, if there is any.
func (c *FakeSelectorSyncIdentityProviders) Create(selectorSyncIdentityProvider *hivev1.SelectorSyncIdentityProvider) (result *hivev1.SelectorSyncIdentityProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(selectorsyncidentityprovidersResource, selectorSyncIdentityProvider), &hivev1.SelectorSyncIdentityProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.SelectorSyncIdentityProvider), err
}

// Update takes the representation of a selectorSyncIdentityProvider and updates it. Returns the server's representation of the selectorSyncIdentityProvider, and an error, if there is any.
func (c *FakeSelectorSyncIdentityProviders) Update(selectorSyncIdentityProvider *hivev1.SelectorSyncIdentityProvider) (result *hivev1.SelectorSyncIdentityProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(selectorsyncidentityprovidersResource, selectorSyncIdentityProvider), &hivev1.SelectorSyncIdentityProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.SelectorSyncIdentityProvider), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSelectorSyncIdentityProviders) UpdateStatus(selectorSyncIdentityProvider *hivev1.SelectorSyncIdentityProvider) (*hivev1.SelectorSyncIdentityProvider, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(selectorsyncidentityprovidersResource, "status", selectorSyncIdentityProvider), &hivev1.SelectorSyncIdentityProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.SelectorSyncIdentityProvider), err
}

// Delete takes name of the selectorSyncIdentityProvider and deletes it. Returns an error if one occurs.
func (c *FakeSelectorSyncIdentityProviders) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(selectorsyncidentityprovidersResource, name), &hivev1.SelectorSyncIdentityProvider{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSelectorSyncIdentityProviders) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(selectorsyncidentityprovidersResource, listOptions)

	_, err := c.Fake.Invokes(action, &hivev1.SelectorSyncIdentityProviderList{})
	return err
}

// Patch applies the patch and returns the patched selectorSyncIdentityProvider.
func (c *FakeSelectorSyncIdentityProviders) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *hivev1.SelectorSyncIdentityProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(selectorsyncidentityprovidersResource, name, pt, data, subresources...), &hivev1.SelectorSyncIdentityProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.SelectorSyncIdentityProvider), err
}
