// Code generated by main. DO NOT EDIT.

package fake

import (
	hivev1 "github.com/openshift/hive/pkg/apis/hive/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterLeasePools implements ClusterLeasePoolInterface
type FakeClusterLeasePools struct {
	Fake *FakeHiveV1
}

var clusterleasepoolsResource = schema.GroupVersionResource{Group: "hive.openshift.io", Version: "v1", Resource: "clusterleasepools"}

var clusterleasepoolsKind = schema.GroupVersionKind{Group: "hive.openshift.io", Version: "v1", Kind: "ClusterLeasePool"}

// Get takes name of the clusterLeasePool, and returns the corresponding clusterLeasePool object, and an error if there is any.
func (c *FakeClusterLeasePools) Get(name string, options v1.GetOptions) (result *hivev1.ClusterLeasePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterleasepoolsResource, name), &hivev1.ClusterLeasePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterLeasePool), err
}

// List takes label and field selectors, and returns the list of ClusterLeasePools that match those selectors.
func (c *FakeClusterLeasePools) List(opts v1.ListOptions) (result *hivev1.ClusterLeasePoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterleasepoolsResource, clusterleasepoolsKind, opts), &hivev1.ClusterLeasePoolList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hivev1.ClusterLeasePoolList{ListMeta: obj.(*hivev1.ClusterLeasePoolList).ListMeta}
	for _, item := range obj.(*hivev1.ClusterLeasePoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterLeasePools.
func (c *FakeClusterLeasePools) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterleasepoolsResource, opts))
}

// Create takes the representation of a clusterLeasePool and creates it.  Returns the server's representation of the clusterLeasePool, and an error, if there is any.
func (c *FakeClusterLeasePools) Create(clusterLeasePool *hivev1.ClusterLeasePool) (result *hivev1.ClusterLeasePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterleasepoolsResource, clusterLeasePool), &hivev1.ClusterLeasePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterLeasePool), err
}

// Update takes the representation of a clusterLeasePool and updates it. Returns the server's representation of the clusterLeasePool, and an error, if there is any.
func (c *FakeClusterLeasePools) Update(clusterLeasePool *hivev1.ClusterLeasePool) (result *hivev1.ClusterLeasePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterleasepoolsResource, clusterLeasePool), &hivev1.ClusterLeasePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterLeasePool), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterLeasePools) UpdateStatus(clusterLeasePool *hivev1.ClusterLeasePool) (*hivev1.ClusterLeasePool, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterleasepoolsResource, "status", clusterLeasePool), &hivev1.ClusterLeasePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterLeasePool), err
}

// Delete takes name of the clusterLeasePool and deletes it. Returns an error if one occurs.
func (c *FakeClusterLeasePools) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clusterleasepoolsResource, name), &hivev1.ClusterLeasePool{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterLeasePools) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterleasepoolsResource, listOptions)

	_, err := c.Fake.Invokes(action, &hivev1.ClusterLeasePoolList{})
	return err
}

// Patch applies the patch and returns the patched clusterLeasePool.
func (c *FakeClusterLeasePools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *hivev1.ClusterLeasePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterleasepoolsResource, name, pt, data, subresources...), &hivev1.ClusterLeasePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterLeasePool), err
}
