// Code generated by main. DO NOT EDIT.

package fake

import (
	hivev1 "github.com/openshift/hive/pkg/apis/hive/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterLeaseRequests implements ClusterLeaseRequestInterface
type FakeClusterLeaseRequests struct {
	Fake *FakeHiveV1
}

var clusterleaserequestsResource = schema.GroupVersionResource{Group: "hive.openshift.io", Version: "v1", Resource: "clusterleaserequests"}

var clusterleaserequestsKind = schema.GroupVersionKind{Group: "hive.openshift.io", Version: "v1", Kind: "ClusterLeaseRequest"}

// Get takes name of the clusterLeaseRequest, and returns the corresponding clusterLeaseRequest object, and an error if there is any.
func (c *FakeClusterLeaseRequests) Get(name string, options v1.GetOptions) (result *hivev1.ClusterLeaseRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterleaserequestsResource, name), &hivev1.ClusterLeaseRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterLeaseRequest), err
}

// List takes label and field selectors, and returns the list of ClusterLeaseRequests that match those selectors.
func (c *FakeClusterLeaseRequests) List(opts v1.ListOptions) (result *hivev1.ClusterLeaseRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterleaserequestsResource, clusterleaserequestsKind, opts), &hivev1.ClusterLeaseRequestList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hivev1.ClusterLeaseRequestList{ListMeta: obj.(*hivev1.ClusterLeaseRequestList).ListMeta}
	for _, item := range obj.(*hivev1.ClusterLeaseRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterLeaseRequests.
func (c *FakeClusterLeaseRequests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterleaserequestsResource, opts))
}

// Create takes the representation of a clusterLeaseRequest and creates it.  Returns the server's representation of the clusterLeaseRequest, and an error, if there is any.
func (c *FakeClusterLeaseRequests) Create(clusterLeaseRequest *hivev1.ClusterLeaseRequest) (result *hivev1.ClusterLeaseRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterleaserequestsResource, clusterLeaseRequest), &hivev1.ClusterLeaseRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterLeaseRequest), err
}

// Update takes the representation of a clusterLeaseRequest and updates it. Returns the server's representation of the clusterLeaseRequest, and an error, if there is any.
func (c *FakeClusterLeaseRequests) Update(clusterLeaseRequest *hivev1.ClusterLeaseRequest) (result *hivev1.ClusterLeaseRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterleaserequestsResource, clusterLeaseRequest), &hivev1.ClusterLeaseRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterLeaseRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterLeaseRequests) UpdateStatus(clusterLeaseRequest *hivev1.ClusterLeaseRequest) (*hivev1.ClusterLeaseRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterleaserequestsResource, "status", clusterLeaseRequest), &hivev1.ClusterLeaseRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterLeaseRequest), err
}

// Delete takes name of the clusterLeaseRequest and deletes it. Returns an error if one occurs.
func (c *FakeClusterLeaseRequests) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clusterleaserequestsResource, name), &hivev1.ClusterLeaseRequest{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterLeaseRequests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterleaserequestsResource, listOptions)

	_, err := c.Fake.Invokes(action, &hivev1.ClusterLeaseRequestList{})
	return err
}

// Patch applies the patch and returns the patched clusterLeaseRequest.
func (c *FakeClusterLeaseRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *hivev1.ClusterLeaseRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterleaserequestsResource, name, pt, data, subresources...), &hivev1.ClusterLeaseRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterLeaseRequest), err
}
