apiVersion: v1
kind: Template
metadata:
  name: additional-hive-regexes
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: additional-install-log-regexes
    data:
      regexes: |
        - name: EIPAddressLimitExceeded
          searchRegexStrings:
            - "EIP: AddressLimitExceeded"
          installFailingReason: EIPAddressLimitExceeded
          installFailingMessage: EIP Address limit exceeded
        - name: InvalidInstallConfigSubnet
          searchRegexStrings:
            - "CIDR range start.*is outside of the specified machine networks"
          installFailingReason: InvalidInstallConfigSubnet
          installFailingMessage: Invalid subnet in install config. Subnet's CIDR range start is outside of the specified machine networks
        - name: InvalidInstallConfig
          searchRegexStrings:
            - "failed to load asset \\\"Install Config\\\""
          installFailingReason: InvalidInstallConfig
          installFailingMessage: Installer failed to load install config
