// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	azure "github.com/openshift/hive/apis/hive/v1/azure"
	v1 "k8s.io/api/core/v1"
)

// AzureDNSZoneSpecApplyConfiguration represents an declarative configuration of the AzureDNSZoneSpec type for use
// with apply.
type AzureDNSZoneSpecApplyConfiguration struct {
	CredentialsSecretRef *v1.LocalObjectReference `json:"credentialsSecretRef,omitempty"`
	ResourceGroupName    *string                  `json:"resourceGroupName,omitempty"`
	CloudName            *azure.CloudEnvironment  `json:"cloudName,omitempty"`
}

// AzureDNSZoneSpecApplyConfiguration constructs an declarative configuration of the AzureDNSZoneSpec type for use with
// apply.
func AzureDNSZoneSpec() *AzureDNSZoneSpecApplyConfiguration {
	return &AzureDNSZoneSpecApplyConfiguration{}
}

// WithCredentialsSecretRef sets the CredentialsSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CredentialsSecretRef field is set to the value of the last call.
func (b *AzureDNSZoneSpecApplyConfiguration) WithCredentialsSecretRef(value v1.LocalObjectReference) *AzureDNSZoneSpecApplyConfiguration {
	b.CredentialsSecretRef = &value
	return b
}

// WithResourceGroupName sets the ResourceGroupName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceGroupName field is set to the value of the last call.
func (b *AzureDNSZoneSpecApplyConfiguration) WithResourceGroupName(value string) *AzureDNSZoneSpecApplyConfiguration {
	b.ResourceGroupName = &value
	return b
}

// WithCloudName sets the CloudName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudName field is set to the value of the last call.
func (b *AzureDNSZoneSpecApplyConfiguration) WithCloudName(value azure.CloudEnvironment) *AzureDNSZoneSpecApplyConfiguration {
	b.CloudName = &value
	return b
}
