// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// BackupReferenceApplyConfiguration represents an declarative configuration of the BackupReference type for use
// with apply.
type BackupReferenceApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// BackupReferenceApplyConfiguration constructs an declarative configuration of the BackupReference type for use with
// apply.
func BackupReference() *BackupReferenceApplyConfiguration {
	return &BackupReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BackupReferenceApplyConfiguration) WithName(value string) *BackupReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *BackupReferenceApplyConfiguration) WithNamespace(value string) *BackupReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}
