// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ClusterDeprovisionSpecApplyConfiguration represents an declarative configuration of the ClusterDeprovisionSpec type for use
// with apply.
type ClusterDeprovisionSpecApplyConfiguration struct {
	InfraID     *string                                       `json:"infraID,omitempty"`
	ClusterID   *string                                       `json:"clusterID,omitempty"`
	ClusterName *string                                       `json:"clusterName,omitempty"`
	Platform    *ClusterDeprovisionPlatformApplyConfiguration `json:"platform,omitempty"`
}

// ClusterDeprovisionSpecApplyConfiguration constructs an declarative configuration of the ClusterDeprovisionSpec type for use with
// apply.
func ClusterDeprovisionSpec() *ClusterDeprovisionSpecApplyConfiguration {
	return &ClusterDeprovisionSpecApplyConfiguration{}
}

// WithInfraID sets the InfraID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InfraID field is set to the value of the last call.
func (b *ClusterDeprovisionSpecApplyConfiguration) WithInfraID(value string) *ClusterDeprovisionSpecApplyConfiguration {
	b.InfraID = &value
	return b
}

// WithClusterID sets the ClusterID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterID field is set to the value of the last call.
func (b *ClusterDeprovisionSpecApplyConfiguration) WithClusterID(value string) *ClusterDeprovisionSpecApplyConfiguration {
	b.ClusterID = &value
	return b
}

// WithClusterName sets the ClusterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterName field is set to the value of the last call.
func (b *ClusterDeprovisionSpecApplyConfiguration) WithClusterName(value string) *ClusterDeprovisionSpecApplyConfiguration {
	b.ClusterName = &value
	return b
}

// WithPlatform sets the Platform field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Platform field is set to the value of the last call.
func (b *ClusterDeprovisionSpecApplyConfiguration) WithPlatform(value *ClusterDeprovisionPlatformApplyConfiguration) *ClusterDeprovisionSpecApplyConfiguration {
	b.Platform = value
	return b
}
