// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/api/core/v1"
)

// ClusterMetadataApplyConfiguration represents an declarative configuration of the ClusterMetadata type for use
// with apply.
type ClusterMetadataApplyConfiguration struct {
	ClusterID                *string                                    `json:"clusterID,omitempty"`
	InfraID                  *string                                    `json:"infraID,omitempty"`
	AdminKubeconfigSecretRef *v1.LocalObjectReference                   `json:"adminKubeconfigSecretRef,omitempty"`
	AdminPasswordSecretRef   *v1.LocalObjectReference                   `json:"adminPasswordSecretRef,omitempty"`
	Platform                 *ClusterPlatformMetadataApplyConfiguration `json:"platform,omitempty"`
}

// ClusterMetadataApplyConfiguration constructs an declarative configuration of the ClusterMetadata type for use with
// apply.
func ClusterMetadata() *ClusterMetadataApplyConfiguration {
	return &ClusterMetadataApplyConfiguration{}
}

// WithClusterID sets the ClusterID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterID field is set to the value of the last call.
func (b *ClusterMetadataApplyConfiguration) WithClusterID(value string) *ClusterMetadataApplyConfiguration {
	b.ClusterID = &value
	return b
}

// WithInfraID sets the InfraID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InfraID field is set to the value of the last call.
func (b *ClusterMetadataApplyConfiguration) WithInfraID(value string) *ClusterMetadataApplyConfiguration {
	b.InfraID = &value
	return b
}

// WithAdminKubeconfigSecretRef sets the AdminKubeconfigSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminKubeconfigSecretRef field is set to the value of the last call.
func (b *ClusterMetadataApplyConfiguration) WithAdminKubeconfigSecretRef(value v1.LocalObjectReference) *ClusterMetadataApplyConfiguration {
	b.AdminKubeconfigSecretRef = &value
	return b
}

// WithAdminPasswordSecretRef sets the AdminPasswordSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminPasswordSecretRef field is set to the value of the last call.
func (b *ClusterMetadataApplyConfiguration) WithAdminPasswordSecretRef(value v1.LocalObjectReference) *ClusterMetadataApplyConfiguration {
	b.AdminPasswordSecretRef = &value
	return b
}

// WithPlatform sets the Platform field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Platform field is set to the value of the last call.
func (b *ClusterMetadataApplyConfiguration) WithPlatform(value *ClusterPlatformMetadataApplyConfiguration) *ClusterMetadataApplyConfiguration {
	b.Platform = value
	return b
}
