// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ClusterImageSetReferenceApplyConfiguration represents an declarative configuration of the ClusterImageSetReference type for use
// with apply.
type ClusterImageSetReferenceApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// ClusterImageSetReferenceApplyConfiguration constructs an declarative configuration of the ClusterImageSetReference type for use with
// apply.
func ClusterImageSetReference() *ClusterImageSetReferenceApplyConfiguration {
	return &ClusterImageSetReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterImageSetReferenceApplyConfiguration) WithName(value string) *ClusterImageSetReferenceApplyConfiguration {
	b.Name = &value
	return b
}
