// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/openshift/hive/apis/hive/v1"
)

// InventoryEntryApplyConfiguration represents an declarative configuration of the InventoryEntry type for use
// with apply.
type InventoryEntryApplyConfiguration struct {
	Kind *v1.InventoryEntryKind `json:"kind,omitempty"`
	Name *string                `json:"name,omitempty"`
}

// InventoryEntryApplyConfiguration constructs an declarative configuration of the InventoryEntry type for use with
// apply.
func InventoryEntry() *InventoryEntryApplyConfiguration {
	return &InventoryEntryApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *InventoryEntryApplyConfiguration) WithKind(value v1.InventoryEntryKind) *InventoryEntryApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *InventoryEntryApplyConfiguration) WithName(value string) *InventoryEntryApplyConfiguration {
	b.Name = &value
	return b
}
