// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ManageDNSConfigApplyConfiguration represents an declarative configuration of the ManageDNSConfig type for use
// with apply.
type ManageDNSConfigApplyConfiguration struct {
	Domains []string                                `json:"domains,omitempty"`
	AWS     *ManageDNSAWSConfigApplyConfiguration   `json:"aws,omitempty"`
	GCP     *ManageDNSGCPConfigApplyConfiguration   `json:"gcp,omitempty"`
	Azure   *ManageDNSAzureConfigApplyConfiguration `json:"azure,omitempty"`
}

// ManageDNSConfigApplyConfiguration constructs an declarative configuration of the ManageDNSConfig type for use with
// apply.
func ManageDNSConfig() *ManageDNSConfigApplyConfiguration {
	return &ManageDNSConfigApplyConfiguration{}
}

// WithDomains adds the given value to the Domains field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Domains field.
func (b *ManageDNSConfigApplyConfiguration) WithDomains(values ...string) *ManageDNSConfigApplyConfiguration {
	for i := range values {
		b.Domains = append(b.Domains, values[i])
	}
	return b
}

// WithAWS sets the AWS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AWS field is set to the value of the last call.
func (b *ManageDNSConfigApplyConfiguration) WithAWS(value *ManageDNSAWSConfigApplyConfiguration) *ManageDNSConfigApplyConfiguration {
	b.AWS = value
	return b
}

// WithGCP sets the GCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GCP field is set to the value of the last call.
func (b *ManageDNSConfigApplyConfiguration) WithGCP(value *ManageDNSGCPConfigApplyConfiguration) *ManageDNSConfigApplyConfiguration {
	b.GCP = value
	return b
}

// WithAzure sets the Azure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Azure field is set to the value of the last call.
func (b *ManageDNSConfigApplyConfiguration) WithAzure(value *ManageDNSAzureConfigApplyConfiguration) *ManageDNSConfigApplyConfiguration {
	b.Azure = value
	return b
}
