// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ReleaseImageVerificationConfigMapReferenceApplyConfiguration represents an declarative configuration of the ReleaseImageVerificationConfigMapReference type for use
// with apply.
type ReleaseImageVerificationConfigMapReferenceApplyConfiguration struct {
	Namespace *string `json:"namespace,omitempty"`
	Name      *string `json:"name,omitempty"`
}

// ReleaseImageVerificationConfigMapReferenceApplyConfiguration constructs an declarative configuration of the ReleaseImageVerificationConfigMapReference type for use with
// apply.
func ReleaseImageVerificationConfigMapReference() *ReleaseImageVerificationConfigMapReferenceApplyConfiguration {
	return &ReleaseImageVerificationConfigMapReferenceApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ReleaseImageVerificationConfigMapReferenceApplyConfiguration) WithNamespace(value string) *ReleaseImageVerificationConfigMapReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ReleaseImageVerificationConfigMapReferenceApplyConfiguration) WithName(value string) *ReleaseImageVerificationConfigMapReferenceApplyConfiguration {
	b.Name = &value
	return b
}
