// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	hivev1 "github.com/openshift/hive/pkg/apis/hive/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterSyncSets implements ClusterSyncSetInterface
type FakeClusterSyncSets struct {
	Fake *FakeHiveV1
	ns   string
}

var clustersyncsetsResource = schema.GroupVersionResource{Group: "hive.openshift.io", Version: "v1", Resource: "clustersyncsets"}

var clustersyncsetsKind = schema.GroupVersionKind{Group: "hive.openshift.io", Version: "v1", Kind: "ClusterSyncSet"}

// Get takes name of the clusterSyncSet, and returns the corresponding clusterSyncSet object, and an error if there is any.
func (c *FakeClusterSyncSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *hivev1.ClusterSyncSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clustersyncsetsResource, c.ns, name), &hivev1.ClusterSyncSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterSyncSet), err
}

// List takes label and field selectors, and returns the list of ClusterSyncSets that match those selectors.
func (c *FakeClusterSyncSets) List(ctx context.Context, opts v1.ListOptions) (result *hivev1.ClusterSyncSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clustersyncsetsResource, clustersyncsetsKind, c.ns, opts), &hivev1.ClusterSyncSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hivev1.ClusterSyncSetList{ListMeta: obj.(*hivev1.ClusterSyncSetList).ListMeta}
	for _, item := range obj.(*hivev1.ClusterSyncSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterSyncSets.
func (c *FakeClusterSyncSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clustersyncsetsResource, c.ns, opts))

}

// Create takes the representation of a clusterSyncSet and creates it.  Returns the server's representation of the clusterSyncSet, and an error, if there is any.
func (c *FakeClusterSyncSets) Create(ctx context.Context, clusterSyncSet *hivev1.ClusterSyncSet, opts v1.CreateOptions) (result *hivev1.ClusterSyncSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clustersyncsetsResource, c.ns, clusterSyncSet), &hivev1.ClusterSyncSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterSyncSet), err
}

// Update takes the representation of a clusterSyncSet and updates it. Returns the server's representation of the clusterSyncSet, and an error, if there is any.
func (c *FakeClusterSyncSets) Update(ctx context.Context, clusterSyncSet *hivev1.ClusterSyncSet, opts v1.UpdateOptions) (result *hivev1.ClusterSyncSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clustersyncsetsResource, c.ns, clusterSyncSet), &hivev1.ClusterSyncSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterSyncSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterSyncSets) UpdateStatus(ctx context.Context, clusterSyncSet *hivev1.ClusterSyncSet, opts v1.UpdateOptions) (*hivev1.ClusterSyncSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clustersyncsetsResource, "status", c.ns, clusterSyncSet), &hivev1.ClusterSyncSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterSyncSet), err
}

// Delete takes name of the clusterSyncSet and deletes it. Returns an error if one occurs.
func (c *FakeClusterSyncSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clustersyncsetsResource, c.ns, name), &hivev1.ClusterSyncSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterSyncSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clustersyncsetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &hivev1.ClusterSyncSetList{})
	return err
}

// Patch applies the patch and returns the patched clusterSyncSet.
func (c *FakeClusterSyncSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *hivev1.ClusterSyncSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clustersyncsetsResource, c.ns, name, pt, data, subresources...), &hivev1.ClusterSyncSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hivev1.ClusterSyncSet), err
}
