// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/openshift/hive/apis/hive/v1"
	hivev1 "github.com/openshift/hive/pkg/client/applyconfiguration/hive/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSelectorSyncSets implements SelectorSyncSetInterface
type FakeSelectorSyncSets struct {
	Fake *FakeHiveV1
}

var selectorsyncsetsResource = v1.SchemeGroupVersion.WithResource("selectorsyncsets")

var selectorsyncsetsKind = v1.SchemeGroupVersion.WithKind("SelectorSyncSet")

// Get takes name of the selectorSyncSet, and returns the corresponding selectorSyncSet object, and an error if there is any.
func (c *FakeSelectorSyncSets) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SelectorSyncSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(selectorsyncsetsResource, name), &v1.SelectorSyncSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SelectorSyncSet), err
}

// List takes label and field selectors, and returns the list of SelectorSyncSets that match those selectors.
func (c *FakeSelectorSyncSets) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SelectorSyncSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(selectorsyncsetsResource, selectorsyncsetsKind, opts), &v1.SelectorSyncSetList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.SelectorSyncSetList{ListMeta: obj.(*v1.SelectorSyncSetList).ListMeta}
	for _, item := range obj.(*v1.SelectorSyncSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested selectorSyncSets.
func (c *FakeSelectorSyncSets) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(selectorsyncsetsResource, opts))
}

// Create takes the representation of a selectorSyncSet and creates it.  Returns the server's representation of the selectorSyncSet, and an error, if there is any.
func (c *FakeSelectorSyncSets) Create(ctx context.Context, selectorSyncSet *v1.SelectorSyncSet, opts metav1.CreateOptions) (result *v1.SelectorSyncSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(selectorsyncsetsResource, selectorSyncSet), &v1.SelectorSyncSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SelectorSyncSet), err
}

// Update takes the representation of a selectorSyncSet and updates it. Returns the server's representation of the selectorSyncSet, and an error, if there is any.
func (c *FakeSelectorSyncSets) Update(ctx context.Context, selectorSyncSet *v1.SelectorSyncSet, opts metav1.UpdateOptions) (result *v1.SelectorSyncSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(selectorsyncsetsResource, selectorSyncSet), &v1.SelectorSyncSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SelectorSyncSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSelectorSyncSets) UpdateStatus(ctx context.Context, selectorSyncSet *v1.SelectorSyncSet, opts metav1.UpdateOptions) (*v1.SelectorSyncSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(selectorsyncsetsResource, "status", selectorSyncSet), &v1.SelectorSyncSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SelectorSyncSet), err
}

// Delete takes name of the selectorSyncSet and deletes it. Returns an error if one occurs.
func (c *FakeSelectorSyncSets) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(selectorsyncsetsResource, name, opts), &v1.SelectorSyncSet{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSelectorSyncSets) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(selectorsyncsetsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.SelectorSyncSetList{})
	return err
}

// Patch applies the patch and returns the patched selectorSyncSet.
func (c *FakeSelectorSyncSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SelectorSyncSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(selectorsyncsetsResource, name, pt, data, subresources...), &v1.SelectorSyncSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SelectorSyncSet), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied selectorSyncSet.
func (c *FakeSelectorSyncSets) Apply(ctx context.Context, selectorSyncSet *hivev1.SelectorSyncSetApplyConfiguration, opts metav1.ApplyOptions) (result *v1.SelectorSyncSet, err error) {
	if selectorSyncSet == nil {
		return nil, fmt.Errorf("selectorSyncSet provided to Apply must not be nil")
	}
	data, err := json.Marshal(selectorSyncSet)
	if err != nil {
		return nil, err
	}
	name := selectorSyncSet.Name
	if name == nil {
		return nil, fmt.Errorf("selectorSyncSet.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(selectorsyncsetsResource, *name, types.ApplyPatchType, data), &v1.SelectorSyncSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SelectorSyncSet), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeSelectorSyncSets) ApplyStatus(ctx context.Context, selectorSyncSet *hivev1.SelectorSyncSetApplyConfiguration, opts metav1.ApplyOptions) (result *v1.SelectorSyncSet, err error) {
	if selectorSyncSet == nil {
		return nil, fmt.Errorf("selectorSyncSet provided to Apply must not be nil")
	}
	data, err := json.Marshal(selectorSyncSet)
	if err != nil {
		return nil, err
	}
	name := selectorSyncSet.Name
	if name == nil {
		return nil, fmt.Errorf("selectorSyncSet.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(selectorsyncsetsResource, *name, types.ApplyPatchType, data, "status"), &v1.SelectorSyncSet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SelectorSyncSet), err
}
