// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift/hive/pkg/client/clientset/versioned/typed/hiveinternal/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeHiveinternalV1alpha1 struct {
	*testing.Fake
}

func (c *FakeHiveinternalV1alpha1) ClusterSyncs(namespace string) v1alpha1.ClusterSyncInterface {
	return &FakeClusterSyncs{c, namespace}
}

func (c *FakeHiveinternalV1alpha1) ClusterSyncLeases(namespace string) v1alpha1.ClusterSyncLeaseInterface {
	return &FakeClusterSyncLeases{c, namespace}
}

func (c *FakeHiveinternalV1alpha1) FakeClusterInstalls(namespace string) v1alpha1.FakeClusterInstallInterface {
	return &FakeFakeClusterInstalls{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeHiveinternalV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
