apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: clusterimagesets.hive.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.hiveImage
    name: Hive
    type: string
  - JSONPath: .status.installerImage
    name: Installer
    type: string
  - JSONPath: .spec.releaseImage
    name: Release
    type: string
  group: hive.openshift.io
  names:
    kind: ClusterImageSet
    plural: clusterimagesets
    shortNames:
    - imgset
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            hiveImage:
              description: HiveImage is the Hive image to use when installing or destroying
                a cluster. If not present, the default Hive image for the clusterdeployment
                controller is used.
              type: string
            installerImage:
              description: InstallerImage is the image used to install a cluster.
                If not specified, the installer image reference is obtained from the
                release image.
              type: string
            releaseImage:
              description: ReleaseImage is the image that contains the payload to
                use when installing a cluster. If the installer image is specified,
                the release image is optional.
              type: string
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
