{
 "title": "Hive SLO",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "env", "query": { "query": "label_values(appsre_env)" } },
   {
    "name": "bucket",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "hive_le", "query": { "query": "label_values(le)" } },
   { "name": "install_le", "query": { "query": "label_values(le)" } },
   { "name": "shard_status", "query": { "query": "label_values(shard_status)" } },
   { "name": "hive_delay_slo", "query": "0.985" },
   { "name": "install_duration_slo", "query": "0.985" },
   { "name": "combined_slo", "query": "0.985" },
   { "name": "percentile", "query": "0.99,0.95,0.90,0.85,0.50" },
   {
    "name": "env_name",
    "label": "Deployment Environment",
    "query": "select env_name from deployments where env_name in ('osd-stage-01','osd-stage-hives02ue1','osd-integration-hivei01ue1',\n'osd-production-hivep01ue1','osd-production-hivep02ue1','osd-production-hivep03uw1','osd-production-hivep04ew2',\n'osd-production-hivep05ue1','osd-production-hivep06uw2','osd-production-hivep07ue2')"
   }
  ]
 },
 "panels": [
  { "title": "Hive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hive $hive_le sec install delay $bucket bucket",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum (rate(hive_cluster_deployment_install_job_delay_seconds_bucket{appsre_env=\"$env\",le=\"$hive_le\",shard_status=\"$shard_status\"}[$bucket])))/(sum (rate(hive_cluster_deployment_install_job_delay_seconds_count{appsre_env=\"$env\",shard_status=\"$shard_status\"}[$bucket])))"
    }
   ]
  },
  {
   "title": "Error Budget $hive_delay_slo % under $hive_le sec",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-((1-((sum (rate(hive_cluster_deployment_install_job_delay_seconds_bucket{appsre_env=\"$env\",le=\"$hive_le\"}[$bucket])))/(sum (rate(hive_cluster_deployment_install_job_delay_seconds_count{appsre_env=\"$env\"}[$bucket])))))/(1-$hive_delay_slo))"
    }
   ]
  },
  { "title": "Installer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Install $install_le sec duration $bucket bucket",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum (rate(hive_cluster_deployment_install_job_duration_seconds_bucket{appsre_env=\"$env\",le=\"$install_le\"}[$bucket])))/(sum (rate(hive_cluster_deployment_install_job_duration_seconds_count{appsre_env=\"$env\"}[$bucket])))"
    }
   ]
  },
  {
   "title": "Error Budget $hive_delay_slo % under $hive_le sec",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-((1-((sum (rate(hive_cluster_deployment_install_job_duration_seconds_bucket{appsre_env=\"$env\",le=\"$install_le\"}[$bucket])))/(sum (rate(hive_cluster_deployment_install_job_duration_seconds_count{appsre_env=\"$env\"}[$bucket])))))/(1-$install_duration_slo))"
    }
   ]
  },
  {
   "title": "Hive Delay Percentiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hive Delay percentile 1d bucket",
     "type": "timeseries",
     "description": "Detail of percentiles for a small bucket",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, (sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_install_job_delay_seconds_bucket{appsre_env=\"$env\",shard_status=\"$shard_status\"}[1d]))))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, (sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_install_job_delay_seconds_bucket{appsre_env=\"$env\",shard_status=\"$shard_status\"}[1d]))))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.90, (sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_install_job_delay_seconds_bucket{appsre_env=\"$env\",shard_status=\"$shard_status\"}[1d]))))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.85, (sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_install_job_delay_seconds_bucket{appsre_env=\"$env\",shard_status=\"$shard_status\"}[1d]))))",
       "legendFormat": "85%"
      },
      {
       "expr": "histogram_quantile(0.5, (sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_install_job_delay_seconds_bucket{appsre_env=\"$env\",shard_status=\"$shard_status\"}[1d]))))",
       "legendFormat": "50%"
      }
     ]
    }
   ]
  },
  {
   "title": "Installer Duration Percentiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Install Duration percentile 1d bucket",
     "type": "timeseries",
     "description": "Detail of percentiles for a small bucket",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, (sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_install_job_duration_seconds_bucket{appsre_env=\"$env\",shard_status=\"$shard_status\"}[1d]))))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, (sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_install_job_duration_seconds_bucket{appsre_env=\"$env\",shard_status=\"$shard_status\"}[1d]))))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.90, (sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_install_job_duration_seconds_bucket{appsre_env=\"$env\",shard_status=\"$shard_status\"}[1d]))))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.85, (sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_install_job_duration_seconds_bucket{appsre_env=\"$env\",shard_status=\"$shard_status\"}[1d]))))",
       "legendFormat": "85%"
      },
      {
       "expr": "histogram_quantile(0.5, (sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_install_job_duration_seconds_bucket{appsre_env=\"$env\",shard_status=\"$shard_status\"}[1d]))))",
       "legendFormat": "50%"
      }
     ]
    }
   ]
  }
 ]
}