// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/openshift/hive/apis/hive/v1"
	hivev1 "github.com/openshift/hive/pkg/client/applyconfiguration/hive/v1"
	scheme "github.com/openshift/hive/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterDeprovisionsGetter has a method to return a ClusterDeprovisionInterface.
// A group's client should implement this interface.
type ClusterDeprovisionsGetter interface {
	ClusterDeprovisions(namespace string) ClusterDeprovisionInterface
}

// ClusterDeprovisionInterface has methods to work with ClusterDeprovision resources.
type ClusterDeprovisionInterface interface {
	Create(ctx context.Context, clusterDeprovision *v1.ClusterDeprovision, opts metav1.CreateOptions) (*v1.ClusterDeprovision, error)
	Update(ctx context.Context, clusterDeprovision *v1.ClusterDeprovision, opts metav1.UpdateOptions) (*v1.ClusterDeprovision, error)
	UpdateStatus(ctx context.Context, clusterDeprovision *v1.ClusterDeprovision, opts metav1.UpdateOptions) (*v1.ClusterDeprovision, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ClusterDeprovision, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ClusterDeprovisionList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClusterDeprovision, err error)
	Apply(ctx context.Context, clusterDeprovision *hivev1.ClusterDeprovisionApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ClusterDeprovision, err error)
	ApplyStatus(ctx context.Context, clusterDeprovision *hivev1.ClusterDeprovisionApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ClusterDeprovision, err error)
	ClusterDeprovisionExpansion
}

// clusterDeprovisions implements ClusterDeprovisionInterface
type clusterDeprovisions struct {
	client rest.Interface
	ns     string
}

// newClusterDeprovisions returns a ClusterDeprovisions
func newClusterDeprovisions(c *HiveV1Client, namespace string) *clusterDeprovisions {
	return &clusterDeprovisions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterDeprovision, and returns the corresponding clusterDeprovision object, and an error if there is any.
func (c *clusterDeprovisions) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ClusterDeprovision, err error) {
	result = &v1.ClusterDeprovision{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterdeprovisions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterDeprovisions that match those selectors.
func (c *clusterDeprovisions) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ClusterDeprovisionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ClusterDeprovisionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterdeprovisions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterDeprovisions.
func (c *clusterDeprovisions) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusterdeprovisions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterDeprovision and creates it.  Returns the server's representation of the clusterDeprovision, and an error, if there is any.
func (c *clusterDeprovisions) Create(ctx context.Context, clusterDeprovision *v1.ClusterDeprovision, opts metav1.CreateOptions) (result *v1.ClusterDeprovision, err error) {
	result = &v1.ClusterDeprovision{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusterdeprovisions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterDeprovision).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterDeprovision and updates it. Returns the server's representation of the clusterDeprovision, and an error, if there is any.
func (c *clusterDeprovisions) Update(ctx context.Context, clusterDeprovision *v1.ClusterDeprovision, opts metav1.UpdateOptions) (result *v1.ClusterDeprovision, err error) {
	result = &v1.ClusterDeprovision{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterdeprovisions").
		Name(clusterDeprovision.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterDeprovision).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterDeprovisions) UpdateStatus(ctx context.Context, clusterDeprovision *v1.ClusterDeprovision, opts metav1.UpdateOptions) (result *v1.ClusterDeprovision, err error) {
	result = &v1.ClusterDeprovision{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterdeprovisions").
		Name(clusterDeprovision.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterDeprovision).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterDeprovision and deletes it. Returns an error if one occurs.
func (c *clusterDeprovisions) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterdeprovisions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterDeprovisions) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterdeprovisions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterDeprovision.
func (c *clusterDeprovisions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClusterDeprovision, err error) {
	result = &v1.ClusterDeprovision{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusterdeprovisions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied clusterDeprovision.
func (c *clusterDeprovisions) Apply(ctx context.Context, clusterDeprovision *hivev1.ClusterDeprovisionApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ClusterDeprovision, err error) {
	if clusterDeprovision == nil {
		return nil, fmt.Errorf("clusterDeprovision provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(clusterDeprovision)
	if err != nil {
		return nil, err
	}
	name := clusterDeprovision.Name
	if name == nil {
		return nil, fmt.Errorf("clusterDeprovision.Name must be provided to Apply")
	}
	result = &v1.ClusterDeprovision{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("clusterdeprovisions").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *clusterDeprovisions) ApplyStatus(ctx context.Context, clusterDeprovision *hivev1.ClusterDeprovisionApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ClusterDeprovision, err error) {
	if clusterDeprovision == nil {
		return nil, fmt.Errorf("clusterDeprovision provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(clusterDeprovision)
	if err != nil {
		return nil, err
	}

	name := clusterDeprovision.Name
	if name == nil {
		return nil, fmt.Errorf("clusterDeprovision.Name must be provided to Apply")
	}

	result = &v1.ClusterDeprovision{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("clusterdeprovisions").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
