apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: hive-operator-0.0.1
  namespace: placeholder
  annotations:
    categories: A list of comma separated categories that your operator falls under.
    certified: "false"
    description: OpenShift cluster provisioning and management at scale.
    containerImage: quay.io/dgoodwin/hive:latest
    createdAt: "2019-02-25T14:29:00Z"
    support: Devan Goodwin
spec:
  displayName: Hive
  description: OpenShift cluster provisioning and management at scale.
  keywords:
  - kubernetes
  - openshift
  - multi-cluster
  - cluster
  version: 0.0.1
  provider:
    name: Red Hat, Inc
  maturity: alpha
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: hive-operator
        # Rules will be added here by the generate-csv.py script.
      deployments:
      - name: hive-operator
        # Deployment spec will be added here by the generate-csv.py script.
  customresourcedefinitions:
    owned:
    - description: Configuration for the Hive Operator
      displayName: Hive Config
      kind: HiveConfig
      name: hiveconfigs.hive.openshift.io
      version: v1
    - description: Defines an OpenShift cluster to be created.
      displayName: Cluster Deployment
      kind: ClusterDeployment
      name: clusterdeployments.hive.openshift.io
      version: v1
    - description: Defines a DNSZone to be managed in a cloud provider.
      displayName: DNS Zone
      kind: DNSZone
      name: dnszones.hive.openshift.io
      version: v1
